-- Media de notas por profesor
SELECT  P.PROFESSOR_ID, CONCAT(P.PROFESSOR_NAME, ' ', P.PROFESSOR_SURNAME) AS 'NOMBRE', AVG(G.GRADE)
FROM PROFESSORS P
JOIN COURSES C
ON P.PROFESSOR_ID = C.PROFESSOR_ID
JOIN GRADES G
ON C.COURSE_ID = G.COURSE_ID
GROUP BY P.PROFESSOR_ID, P.PROFESSOR_NAME, P.PROFESSOR_SURNAME;

-- Mejor nota por estudiante
SELECT S.STUDENT_ID, CONCAT(S.STUDENT_NAME, ' ', S.STUDENT_SURNAME) AS 'NOMBRE', MAX(G.GRADE) AS 'MEJOR NOTA'
FROM STUDENTS S
JOIN GRADES G
ON S.STUDENT_ID = G.STUDENT_ID
GROUP BY	S.STUDENT_ID, S.STUDENT_NAME, S.STUDENT_SURNAME;

-- Ordenar estudiantes por cursos inscritos
SELECT S.STUDENT_ID, CONCAT(S.STUDENT_NAME, ' ', S.STUDENT_SURNAME) AS 'NOMBRE', COURSE_NAME
FROM STUDENTS S
JOIN GRADES G
ON S.STUDENT_ID = G.STUDENT_ID
JOIN COURSES C
ON G.COURSE_ID = C.COURSE_ID
ORDER BY S.STUDENT_ID, C.COURSE_NAME;

-- Resumen de grados y notas medias. ordenado de curso con peor notas a mejor
SELECT C.COURSE_ID, C.COURSE_NAME, AVG(G.GRADE) AS NOTA_MEDIA
FROM COURSES C
JOIN GRADES G
ON C.COURSE_ID = G.COURSE_ID
GROUP BY C.COURSE_ID, C. COURSE_NAME
ORDER BY NOTA_MEDIA ASC;

-- Estudiante y profesor que tienen más asignaturas en común
SELECT CONCAT(S.STUDENT_NAME, ' ', S.STUDENT_SURNAME) AS 'NOMBRE ESTUDIANTE', 
	CONCAT(P.PROFESSOR_NAME, ' ', P.PROFESSOR_SURNAME) AS 'NOMBRE PROFESOR',
       COUNT(*) AS CURSOS_COMUN
FROM COURSES C
JOIN PROFESSORS P
ON P.PROFESSOR_ID = C.PROFESSOR_ID
JOIN GRADES G
ON G.COURSE_ID =C.COURSE_ID
JOIN STUDENTS S
ON G.STUDENT_ID = S.STUDENT_ID
GROUP BY S.STUDENT_NAME, S.STUDENT_SURNAME, P.PROFESSOR_NAME, P.PROFESSOR_SURNAME
ORDER BY CURSOS_COMUN DESC;

